//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XElement.SDM.UI.Win32.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XElement.SDM.UI.Win32.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay startup.
        /// </summary>
        public static string ManagementUC_DelayButton_ToolTip {
            get {
                return ResourceManager.GetString("ManagementUC_DelayButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed by operating system.
        /// </summary>
        public static string ManagementUC_OsLabel_Content {
            get {
                return ResourceManager.GetString("ManagementUC_OsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote startup.
        /// </summary>
        public static string ManagementUC_PromoteButton_ToolTip {
            get {
                return ResourceManager.GetString("ManagementUC_PromoteButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed by this application.
        /// </summary>
        public static string ManagementUC_SdmLabel_Content {
            get {
                return ResourceManager.GetString("ManagementUC_SdmLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all users.
        /// </summary>
        public static string ProgramInfoUC_AllUsersImage_ToolTip {
            get {
                return ResourceManager.GetString("ProgramInfoUC_AllUsersImage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application title:.
        /// </summary>
        public static string ProgramInfoUC_ApplicationLabel_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_ApplicationLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        public static string ProgramInfoUC_ArgumentsLabel_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_ArgumentsLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string ProgramInfoUC_CompanyLabel_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_CompanyLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the current user.
        /// </summary>
        public static string ProgramInfoUC_CurrentUserImage_ToolTip {
            get {
                return ResourceManager.GetString("ProgramInfoUC_CurrentUserImage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ProgramInfoUC_NoCmdArguments_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_NoCmdArguments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin:.
        /// </summary>
        public static string ProgramInfoUC_OriginLabel_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_OriginLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:.
        /// </summary>
        public static string ProgramInfoUC_TargetLabel_Text {
            get {
                return ResourceManager.GetString("ProgramInfoUC_TargetLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit this application?.
        /// </summary>
        public static string TaskbarIconUC_ExitConfirmation_Caption {
            get {
                return ResourceManager.GetString("TaskbarIconUC_ExitConfirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you close this application, all managed applications that have not been started yet won&apos;t be started.
        ///Are you sure?.
        /// </summary>
        public static string TaskbarIconUC_ExitConfirmation_Text {
            get {
                return ResourceManager.GetString("TaskbarIconUC_ExitConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TaskbarIconUC_ExitMenuItem_Header {
            get {
                return ResourceManager.GetString("TaskbarIconUC_ExitMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open….
        /// </summary>
        public static string TaskbarIconUC_ShowMenuItem_Header {
            get {
                return ResourceManager.GetString("TaskbarIconUC_ShowMenuItem_Header", resourceCulture);
            }
        }
    }
}
